src/Entity/Event.php
<?php

namespace App\Entity;

use ApiPlatform\Core\Annotation\ApiResource;
use App\Repository\EventRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Groups;

/**
 * @ORM\Entity(repositoryClass=EventRepository::class)*
 * @ApiResource(
 *     collectionOperations={"get"={"normalization_context"={"groups"="events:list"}}},
 *     itemOperations={
 *      "delete", "get"={"normalization_context"={"groups"="events:item"}}},
 *     paginationEnabled=false
 * )
 */
class Event
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     *
     * @Groups({"events:list", "events:item"})
     */
    private $id;

    /**
     * @ORM\Column(type="datetime")
     *
     * @Groups({"events:list", "events:item"})
     */
    private $scheduler_datetime;

    /**
     * @ORM\ManyToOne(targetEntity=PackAccount::class, inversedBy="events")
     * @ORM\JoinColumn(nullable=false)
     *
     * @Groups({"events:list", "events:item"})
     */
    private $account;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getSchedulerDatetime(): ?\DateTimeInterface
    {
        return $this->scheduler_datetime;
    }

    public function setSchedulerDatetime(\DateTimeInterface $scheduler_datetime): self
    {
        $this->scheduler_datetime = $scheduler_datetime;

        return $this;
    }

    public function getAccount(): ?PackAccount
    {
        return $this->account;
    }

    public function setAccount(?PackAccount $account): self
    {
        $this->account = $account;

        return $this;
    }
}

src/Controller/CalendarController.php
<?php

namespace App\Controller;

use App\Calendar\Calendar;
use App\Entity\Event;
use App\Entity\PackAccount;
use App\Form\EventAddType;
use App\Repository\PackAccountRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class CalendarController extends AbstractController
{

    /**
     * @Route("/user/calendar", name="logged_no_params_calendar")
     */
    public function noParamsCalendar(){
        return $this->redirectToRoute('logged_calendar', ['slug' => date('m', time()) . '-' . date('Y', time())]);
    }

    /**
     * @Route("/user/calendar/previous/{slug}", name="logged_previous_calendar")
     * @param string $slug
     * @return RedirectResponse
     */
    public function previousCalendar(string $slug){
        $month = intval(explode('-', $slug)[0]);
        $year = intval(explode('-', $slug)[1]);

        if($month == 1){
            $month = 12;
            $year -= 1;
        }else{
            $month -= 1;
        }

        return $this->redirectToRoute('logged_calendar', ['slug' => $month . '-' . $year]);

    }

    /**
     * @Route("/user/calendar/next/{slug}", name="logged_next_calendar")
     * @param string $slug
     * @return RedirectResponse
     */
    public function nextCalendar(string $slug){
        $month = intval(explode('-', $slug)[0]);
        $year = intval(explode('-', $slug)[1]);

        if($month == 12){
            $month = 1;
            $year += 1;
        }else{
            $month += 1;
        }

        return $this->redirectToRoute('logged_calendar', ['slug' => $month . '-' . $year]);
    }

    /**
     * @Route("/user/calendar/{slug}", name="logged_calendar")
     * @param string $slug
     * @return Response
     */
    public function index(string $slug)
    {

        $calendar = new Calendar();

        $events = $this->getDoctrine()->getRepository(Event::class)->findAll();

        $month = @intval(explode('-', $slug)[0]);
        $year = @intval(explode('-', $slug)[1]);

        if(!str_contains($slug, '-')){
            $month = date('m', time());
            $year = date('Y', time());
        }else{
            if(!is_int($month) || $month < 1 || $month > 12){
                $month = date('m', time());
            }

            if(!is_int($year) || $year < 1){
                $year = date('Y', time());
            }
        }

        $user_events = [];

        $i = 0;
        foreach ($events as $event){
            if($event->getAccount()->getUserId() == $this->getUser()){
                $user_events[$i] = $event;
                $i++;
            }
        }

        return $this->render('calendar/index.html.twig', [
            'response' => $calendar->createView($month, $year),
            'month' => $month,
            'year' => $year,
            'events' => $user_events
        ]);
    }

    /**
     * @Route("/user/calendar/event/add", name="logged_calendar_add_event")
     * @param Request $request
     * @return Response
     */
    public function addEvent(Request $request){

        $form = $this->createForm(EventAddType::class, null, ['user' => $this->getUser()]);
        $form->handleRequest($request);

        $event = new Event();

        $manager = $this->getDoctrine()->getManager();

        if($form->isSubmitted() && $form->isValid()){

            $event->setAccount($form->get('account')->getData());
            $event->setSchedulerDatetime($form->get('scheduler_datetime')->getData());

            $manager->persist($event);
            $manager->flush();

            return $this->redirectToRoute('logged_no_params_calendar');
        }

        return $this->render('calendar/addEvent.html.twig', [
            'form' => $form->createView()
        ]);
    }
}

templates/calendar/addEvent.html.twig
{% extends 'base.html.twig' %}

{% block title %}PMC Calendar{% endblock %}

{% block stylesheets %}

    <link rel="stylesheet" href="{{ asset('css/calendar.css') }}">

{% endblock %}


{% block body %}


    <div class="container">

        <br>

        <h1>Add new event</h1>

        <br>

        {{ form_start(form) }}

            {{ form_row(form.account) }}
            {{ form_row(form.scheduler_datetime) }}


            <div class="text-center">

                <button class="btn btn-lg btn-primary" type="submit">
                    Add new event
                </button>

            </div>

        {{ form_end(form) }}

    </div>

{% endblock %}

templates/calendar/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}PMC Calendar{% endblock %}

{% block stylesheets %}

    <link rel="stylesheet" href="{{ asset('css/calendar.css') }}">

{% endblock %}


{% block body %}


    <div class="container">

        <br>

        <h1>{% if (date() | date('m')) == month %}{{ response['current_day'] }}{% endif %} {{ response['months'][month - 1] }} {{ year }}</h1>

        <table class="table">
            <tbody>

            <tr>

                {% for i in 1..response['daysInMonths'] %}

                {% if i is divisible by(7) and i != 1 %}

                <td>
                    {% if i <= 7 %}
                        <span class="font-weight-bold">{{ response['days'][i - 1] }}</span>
                        <br>
                    {% endif %}
                    <a href="">
                        <span class="{% if i == response['current_day'] %}__current_day{% else %}__days_number{% endif %}">{{ i }}</span>
                    </a>
                    <br>
                    {% for event in events %}

                        {% if i == (event.schedulerDatetime | date("d")) and (date() | date('m')) == (event.schedulerDateTime('m'))   %}
                            <small class="text-muted">
                                {{ event.account.AccountUsername }} {{ event.schedulerDateTime | date("h:m") }}
                            </small>
                            <br>
                        {% endif %}
                    {% endfor %}
                </td>
            </tr>
            <tr>
                {% else %}
                    <td>
                        {% if i <= 7 %}
                            <span class="font-weight-bold">{{ response['days'][i - 1] }}</span>
                            <br>
                        {% endif %}
                        <a href="">
                            <span class="{% if i == response['current_day'] %}__current_day{% else %}__days_number{% endif %}">{{ i }}</span>
                        </a>
                        <br>

                        <!-- and i == (event.schedulerDatetime | date("m")) -->
                        <!-- ATTENTION LES EVENTS NE SONT PAS AU BON MOIS -->
                        {% for event in events %}

                            {% if (i == (event.schedulerDatetime | date("d")) and (date() | date('m')) == (event.schedulerDateTime('m'))  %}
                                <small class="text-muted">
                                    {{ event.account.AccountUsername }} {{ event.schedulerDateTime | date("h:m") }}
                                </small>
                                <br>
                            {% endif %}
                        {% endfor %}
                    </td>
                {% endif %}

                {% endfor %}


            </tbody>
        </table>
    </div>

    <button type="button" onclick="location.href='{{ path('logged_calendar_add_event')}}'"
            class="btn btn-info btn-circle btn-xl __new_event"><i class="fa fa-check"></i>
    </button>

    <button type="button" onclick="location.href='{{ path('logged_previous_calendar', {'slug': month ~ '-' ~ year}) }}'" class="btn btn-info btn-circle btn-xl" ><i class="fas fa-arrow-left __previous_arrow"></i></button>
    <button type="button" onclick="location.href='{{ path('logged_next_calendar', {'slug': month ~ '-' ~ year}) }}'" class="btn btn-info btn-circle btn-xl" ><i class="fas fa-arrow-right __next_arrow"></i></button>

{% endblock %}